image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
  - command: git config --global user.email $GIT_COMMITTER_EMAIL

vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - vscodevim.vim@1.17.1:9GrHtaCR1xXAlopLzQjIkQ==