[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF website"

[context.production]
  publish = "website/"

[context.deploy-preview]
  publish = "website/"

[context.branch-deploy]
  publish = "website/"

[[redirects]]
  from = "/pages/news"
  to = "/news"

[[plugins]]
package="netlify-plugin-subfont"
  [plugins.inputs]
  inlineCss = true
  inlineFonts = true
