# A basic redirect rule
[[redirects]]
  from = "/pages/news"
  to = "/news"

[[plugins]]
package="netlify-plugin-subfont"
  [plugins.inputs]
  inlineCss = true
  inlineFonts = true

[[plugins]]
package="netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = ["preconnect-check"]
