---
'':
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: ALIAS
  value: apex-loadbalancer.netlify.com.

_acme-challenge.analytics:
  octodns:
    cloudflare:
      proxied: true
  ttl: 300
  type: CNAME
  value: analytics.bobber.fyi.2x6ez0.flydns.net.

analytics:
  octodns:
    cloudflare:
      proxied: true
  ttl: 300
  type: CNAME
  value: grace-bobber-analytics-frontend.fly.dev.

links:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: CNAME
  value: stirring-sprinkles-16b7be.netlify.app.
