---
'':
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: CNAME
  value: stirring-sprinkles-16b7be.netlify.app.

www:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: CNAME
  value: stirring-sprinkles-16b7be.netlify.app.

analytics:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: CNAME
  value: grace-bobber-analytics.netlify.app.
