---
'':
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  type: ALIAS
  value: apex-loadbalancer.netlify.com.

analytics:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  type: CNAME
  value: grace-bobber-analytics-frontend.fly.dev.
links:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  type: CNAME
  value: stirring-sprinkles-16b7be.netlify.app.
