[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./."

[[redirects]]
  from = "/pages/news"
  to = "/news"

[[plugins]]
package="netlify-plugin-subfont"
  [plugins.inputs]
  inlineCss = true
  inlineFonts = true
