name: Deploy Analytics
on:
  push:
    branches:
      - main
    paths:
      - 'analytics/fly.toml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            analytics
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./analytics
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
