name: octodns-sync

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**.yaml'

jobs:
  publish:
    name: Publish DNS config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Apply DNS
        working-directory: ./dns
        run: |
          pip install -r requirements.txt
          octodns-sync \
            --config-file=./config/octodns.yml \
            --doit
        env:
          CLOUDFLARE_TOKEN:  ${{ secrets.CLOUDFLARE_TOKEN }}
