name: octodns-sync

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**.yaml'

jobs:
  publish:
    name: Publish DNS config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r dns/requirements.txt
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: public.yaml
          doit: '--doit'
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
